feat(l1ab-radio-aggregator): new processor
CSC-PS-S2/s2-workflow pull request #27
Opened 2021-11-03 13:17 UTC by glmxndr

2021-11-03 16:51 UTC, ilaborie approved these changes
Few questions, I'm not (yet) aware on the project code convention, sorry for the noise

2021-11-03 16:51 UTC, ilaborie commented on applications/processor/l1ab-radio-aggregator/src/main/java/com/csgroup/s2pdgs/l1abradio/aggregator/L1abRadioAggregator.java
> +            .doOnError(TimeoutException.class, t -> LOGGER.error("Timeout on aggregation for id={}", productId))
Question: do we have an error topic to redirect on timeout ?

2021-11-03 16:51 UTC, ilaborie commented on applications/processor/l1ab-radio-aggregator/src/main/java/com/csgroup/s2pdgs/l1abradio/aggregator/L1abRadioAggregator.java
> +        result.setParallelizationDescription(parallelDesc);
Question: Are we allowed to mutate the parameter like that ?

2021-11-03 16:51 UTC, ilaborie commented on applications/processor/l1ab-radio-aggregator/src/test/java/com/csgroup/s2pdgs/l1abradio/aggregator/data/InputGenerator.java
> +            result.setId(id); result.setName(id);
Maybe: a new line between instructions

2021-11-03 16:51 UTC, ilaborie commented on applications/test-workflow/src/test/java/com/csgroup/s2pdgs/L0WorkflowTest.java
> +        // FIXME
Maybe: fix it or link to a task that should fix it

2021-11-03 16:51 UTC, ilaborie commented on common/messages/src/main/java/com/csgroup/s2pdgs/assets/ParallelizationDescription.java
> +    private S2Detector detectorToTreat = S2Detector.D01;
Question: is it safe to define a default value here ?

2021-11-03 16:51 UTC, ilaborie commented on pom.xml
> +            <version>1.11.21</version>
Question: this is weird to have a != version for byte-buddy and byte-buddy-agent, are you sure ?

2021-11-03 17:24 UTC, glmxndr commented on applications/processor/l1ab-radio-aggregator/src/main/java/com/csgroup/s2pdgs/l1abradio/aggregator/L1abRadioAggregator.java
> +            .doOnError(TimeoutException.class, t -> LOGGER.error("Timeout on aggregation for id={}", productId))
Not reallyspecifically on timeout. The status of the message here is a bit fuzzy, but it could be wrapped in an ErrorMessage and spring cloud stream would (I think) redirect it to the error.xxx topic (if xxx is the input topic).

https://docs.spring.io/spring-cloud-stream-binder-kafka/docs/3.0.10.RELEASE/reference/html/spring-cloud-stream-binder-kafka.html#kafka-error-channels

2021-11-03 17:26 UTC, glmxndr commented on applications/processor/l1ab-radio-aggregator/src/main/java/com/csgroup/s2pdgs/l1abradio/aggregator/L1abRadioAggregator.java
> +        result.setParallelizationDescription(parallelDesc);
We must, as long as we don't have immutable message classes.

2021-11-03 17:27 UTC, glmxndr commented on applications/test-workflow/src/test/java/com/csgroup/s2pdgs/L0WorkflowTest.java
> +        // FIXME
I'll do it next, I'm about to work on tests now. But indeed this part broke compilation.

2021-11-03 17:29 UTC, glmxndr commented on common/messages/src/main/java/com/csgroup/s2pdgs/assets/ParallelizationDescription.java
> +    private S2Detector detectorToTreat = S2Detector.D01;
No (but leaving null is not safer I guess).

2021-11-03 17:31 UTC, glmxndr commented on pom.xml
> +            <version>1.11.21</version>
Nope. But that is the version byte-buddy-agent:1.11.22 depends on. 
https://search.maven.org/artifact/net.bytebuddy/byte-buddy-agent/1.11.22/jar

2021-11-04 06:10 UTC, ilaborie requested changes

2021-11-04 06:10 UTC, ilaborie commented on applications/processor/l1ab-radio-aggregator/src/main/java/com/csgroup/s2pdgs/l1abradio/aggregator/L1abRadioAggregator.java
> +            .filter(FluxScanValue.class::isInstance)
I think that you could replace the filter & cast by the `ofType` operator:
https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#ofType-java.lang.Class-

2021-11-04 08:02 UTC, glmxndr commented on applications/processor/l1ab-radio-aggregator/src/main/java/com/csgroup/s2pdgs/l1abradio/aggregator/L1abRadioAggregator.java
> +            .filter(FluxScanValue.class::isInstance)
Done.

2021-11-04 08:04 UTC, glmxndr commented on common/messages/src/main/java/com/csgroup/s2pdgs/fp/FpUtils.java
> +        return Try.sequence(ts).map(Seq::toList);
Changed the implementation because suddenly @ilaborie likes mutable references and for loops. :)

2021-11-04 08:13 UTC, ilaborie commented on common/messages/src/main/java/com/csgroup/s2pdgs/fp/FpUtils.java
> +        return Try.sequence(ts).map(Seq::toList);
for my psychological well-being, I prefer not to watch how Vavr implements it

2021-11-04 09:15 UTC, ilaborie approved these changes

2021-11-04 09:23 UTC, merged