Bes l1 streams definitions
CSC-PS-S2/s2-workflow pull request #29
Opened 2021-11-04 09:39 UTC by BenEsquis

Adding definitions of the L1 streams

2021-11-04 09:51 UTC, glmxndr commented on scripts/scdf-shell/l1b/destroy.shell
> +stream destroy --name ${S2USER}-l0-raw-to-l0c
--name should be "${S2USER}-l1b-refining"

2021-11-04 13:37 UTC, glmxndr commented on scripts/scdf-shell/inventory-l1b/create.shell
> +  --name "${S2USER}-l0-inventory-gr" \
Stream name seems incoherent.

2021-11-04 13:37 UTC, glmxndr commented on scripts/scdf-shell/inventory-l1b/deploy.shell
> +stream deploy --name ${S2USER}-l1a-inventory-ds --platformName ${PLATFORM_DEFAULT} --properties "\
Stream name seems incoherent.

2021-11-04 13:37 UTC, glmxndr commented on scripts/scdf-shell/inventory-l1b/deploy.shell
> +stream deploy --name ${S2USER}-l1a-inventory-gr --platformName ${PLATFORM_DEFAULT} --properties "\
Stream name seems incoherent.

2021-11-04 13:39 UTC, glmxndr requested changes
Stream name seems incoherent.

2021-11-05 07:06 UTC, BenEsquis commented
Corrected the typos

2021-11-05 07:27 UTC, glmxndr approved these changes

2021-11-05 07:28 UTC, merged