Corrected index not found at startup
CSC-PS-S2/s2-workflow pull request #30
Opened 2021-11-04 09:51 UTC by BenEsquis

Fix the issue when the index doesn't exist at startup for sources

2021-11-04 13:49 UTC, glmxndr requested changes

2021-11-04 13:49 UTC, glmxndr commented on common/auxip-ingestion/src/main/java/com/csgroup/s2pdgs/auxip/ingestion/AuxipFilesIngestion.java
> +                                .thenReturn(UNIT));
Here the `thenReturn` explicitly throws away the IndexNotFoundException. probably not what you intend to do.

Did you mean something like this?

```java
private Mono<Unit> refreshedIndex() {
        return this.clientManager.monoWithCatalogClient(
            this.catalog,
            client -> client.refreshIndex(this.auxIndex)
            .onErrorResume(
                        IndexNotFoundException.class,
                        t -> client.createIndex(auxIndex)
                                .flatMap(b -> {
                                    if (!b) {
                                        return Mono.error(new IndexNotFoundException());
                                    }
                                    return Mono.just(UNIT); 
                                }));
    }
```

2021-11-04 13:49 UTC, glmxndr commented on common/connect/src/main/java/com/csgroup/s2pdgs/station/StationProductsFinder.java
> +                        .thenReturn(UNIT));
Same problem as above.

2021-11-04 13:49 UTC, glmxndr commented on common/connect/src/main/java/com/csgroup/s2pdgs/repository/FTPSRepository.java
> +            log.debug("Using certificate : "+config.getFtpServerCertificateStorePath());
Avoid concatenation in log method (use `{}` instead).

2021-11-04 13:49 UTC, glmxndr commented on applications/source/station-source/src/main/java/com/csgroup/s2pdgs/stationsource/StationPoller.java
> +            log.info("Connecting to repository with configuration : "+configuration.getClass().getCanonicalName());
Avoid concatenation in log methods.

2021-11-04 15:26 UTC, ilaborie commented on applications/source/station-source/src/main/java/com/csgroup/s2pdgs/stationsource/StationPoller.java
> +            .doOnNext(r -> log.debug("connectedRepo: {}", r))
Maybe: use of one `Mono#log` function ?

https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#log--

2021-11-04 15:37 UTC, glmxndr commented on applications/source/station-source/src/main/java/com/csgroup/s2pdgs/stationsource/StationPoller.java
> +            .doOnNext(r -> log.debug("connectedRepo: {}", r))
The Flux/Mono `log()` methods don't allow formatting of the message, and require to provide which types of messages you are interested in (by default they provide subscriptions, requests and complete signals). To me they serve a different purpose than what is done here: they allow to inspect what happens in the reactor layer.

2021-11-04 15:41 UTC, ilaborie commented on applications/source/station-source/src/main/java/com/csgroup/s2pdgs/stationsource/StationPoller.java
> +            .doOnNext(r -> log.debug("connectedRepo: {}", r))
OK

2021-11-05 07:12 UTC, BenEsquis commented on common/auxip-ingestion/src/main/java/com/csgroup/s2pdgs/auxip/ingestion/AuxipFilesIngestion.java
> +                                .thenReturn(UNIT));
Il me semblait que le thenReturn ne renvoyait UNIT que lorsque c'était en success sinon il renvois le Mono<Error> ?
Mais en effet t'a version semble plus explicite.

2021-11-05 08:27 UTC, glmxndr approved these changes

2021-11-05 08:27 UTC, merged